Första fungerande version av meshning
PUM-9/mesh_generator pull request #1
Opened 2017-03-02 11:49 UTC by m-lundberg

Nu fungerar meshning av punktmoln. main fungerar som en service som estimerar normaler till ett punktmoln och använder sedan Poisson surface reconstruction för att skapa en mesh.

test_client kan användas för att testa servicen. Den läser in punktmoln från filer och skickar till servicen och sparar den mesh den får tillbaka till .stl-filer.

Har testats med filerna lamppost.pcd, ism_test_cat.pcd och ism_test_wolf.pcd från https://github.com/PointCloudLibrary/data . Alla filerna fungerar men blir inte helt korrekta. Det kan bero på att filerna har för få punkter. Vi kommer behöva testa med våra egna punktmoln och justera parametrar för att få det att fungera bra men just nu fungerar meshningen i alla fall.

2017-03-02 17:02 UTC, Dunstrom reviewed
Ser bra ut, bara några saker jag inte förstår när jag inte är så insatt i meshning. Se om ni håller med om mina kommentarer eller inte. :+1:

2017-03-02 17:02 UTC, Dunstrom commented on src/main.cpp
> +    // Reverse the direction of all normals
Varför ska man vända på normalerna?

2017-03-02 17:02 UTC, Dunstrom commented on src/main.cpp
> + * @param mesh The resulting 3D-mesh is saved to mesh
Vad menas med att den resulterande 3D-meshen blir sparad till en mesh? Är det inte redan en mesh eller?

2017-03-02 17:02 UTC, Dunstrom commented on src/main.cpp
> +    normal_estimation.setKSearch(20);
Vad är KSearch? Jag kan säkert ta reda på det men funderar på om en kort kommentar kunde vara bra här vad tycker ni?

2017-03-02 17:02 UTC, Dunstrom commented on src/main.cpp
> +    poisson.setDepth(9);
Samma här som KSearch, vet inte vad Depth gör här, kan man klargöra med en kort kommentar?

2017-03-02 18:07 UTC, FredrikWallstrom reviewed
Jag tycker det ser bra ut, bra jobbat! 👍

2017-03-02 18:07 UTC, FredrikWallstrom commented on src/main.cpp
> +
Bagatell, men onödig tom rad?

2017-03-02 18:07 UTC, FredrikWallstrom commented on src/main.cpp
> +    normal_estimation.setKSearch(20);
Jag kan hålla med, en kort kommentar vore bra 👍

2017-03-05 16:14 UTC, m-lundberg commented on src/main.cpp
> + * @param mesh The resulting 3D-mesh is saved to mesh
Var lite otydligt förklarat, det menas att resultatet av meshningen sparas till objektet som heter mesh (som skickas in som argument via en referens så man kommer åt resultatet även utanför funktionen).

2017-03-06 13:57 UTC, Dunstrom requested changes
Fixa multiline kommentarer så är jag nöjd :+1:

2017-03-06 13:57 UTC, Dunstrom commented on src/main.cpp
> +    // too low a number will cause problems.
multiline comment please :kiss:

2017-03-06 14:10 UTC, Dunstrom approved these changes
:+1:

2017-03-06 14:10 UTC, merged